module.exports = {
  siteMetadata: {
    title: `gatsby-plugin-content-hash-example`,
    author: {
      name: `sititou70`,
      summary: `Author of gatsby-plugin-content-hash.`,
    },
    description: `Add content hash to requests for app-data.json and page-data.json generated by Gatsby.`,
    siteUrl: `https://gatsbystarterblogsource.gatsbyjs.io/`,
    social: {
      twitter: `sititou70`,
    },
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
    },
    {
      resolve: "gatsby-plugin-content-hash",
      options: { build_root_path: `${__dirname}/public` },
    },
  ],
}
